name: CI

on:
  push:
    branches: ["mathlib4"]
  
  pull_request:
    branches: ["main"]

jobs:
  make_all_proof_sources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - name: Run proof sources script
        run: |
          ./util/make-all-proof-sources.sh
      - name: Compress proof sources 
        run: |
          zip -r proof_sources.zip data/proof_sources
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: proof_sources 
          path: proof_sources.zip

  extract_data_1:
    needs: make_all_proof_sources
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - uses: actions/download-artifact@v3
        with:
          name: proof_sources
      - name: Unzip proof sources 
        run: |
          unzip proof_sources.zip
      - name: Extract data from modules 0-999
        run: |
          ./util/extract-from-modules-range.sh 0 999
  
  # extract_data_2:
  #   needs: make_all_proof_sources
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: ./.github/actions/build
  #     - name: Extract data from modules 1000-1999
  #       run: |
  #         ./util/extract-from-modules-range.sh 1000 1999
  
  # extract_data_3:
  #   needs: make_all_proof_sources
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: ./.github/actions/build
  #     - name: Extract data from modules 2000-2999
  #       run: |
  #         ./util/extract-from-modules-range.sh 2000 2999
  
  # extract_data_4:
  #   needs: make_all_proof_sources
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: ./.github/actions/build
  #     - name: Extract data from modules 3000-3999
  #       run: |
  #         ./util/extract-from-modules-range.sh 3000 3999
